/**
 * ICure Medical Device Micro Service
 *
 * ICure Medical Device Micro Service
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.md.client.models


import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.github.pozo.KotlinBuilder

/**
 * 
 *
 * @param id 
 * @param qualifiedLinks 
 * @param searchTerms 
 * @param rev 
 * @param type 
 * @param code 
 * @param version 
 * @param description 
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@KotlinBuilder
data class Coding (

    @field:JsonProperty("id")
    val id: String,

    @field:JsonProperty("qualifiedLinks")
    val qualifiedLinks: Map<String, List<String>> = emptyMap(),

    @field:JsonProperty("searchTerms")
    val searchTerms: Map<String, Set<String>> = emptyMap(),

    @field:JsonProperty("rev")
    val rev: String? = null,

    @field:JsonProperty("type")
    val type: String? = null,

    @field:JsonProperty("code")
    val code: String? = null,

    @field:JsonProperty("version")
    val version: String? = null,

    @field:JsonProperty("description")
    val description: Map<String, String>? = null

)

