/**
 * ICure Medical Device Micro Service
 *
 * ICure Medical Device Micro Service
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.md.client.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.github.pozo.KotlinBuilder

/**
 * 
 *
 * @param id The Id of the document. We encourage using either a v4 UUID or a HL7 Id.
 * @param labels 
 * @param codes 
 * @param otherUtis Extra Uniform Type Identifiers
 * @param rev The revision of the document in the database, used for conflict management / optimistic locking.
 * @param created 
 * @param modified 
 * @param author 
 * @param responsible 
 * @param medicalLocationId 
 * @param endOfLife 
 * @param deletionDate 
 * @param objectStoreReference Reference in object store
 * @param externalUri When the document is stored in an external repository, this is the uri of the document in that repository
 * @param mainUti The main Uniform Type Identifier of the document (https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE)
 * @param name Name of the document
 * @param version The document version
 * @param externalUuid A unique external id (from another external source).
 * @param propertySize Size of the document file
 * @param hash Hashed version of the document
 * @param attachmentId Id of attachment to this document
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@KotlinBuilder
data class Document (

    /* The Id of the document. We encourage using either a v4 UUID or a HL7 Id. */
    @field:JsonProperty("id")
    val id: String?,

    @field:JsonProperty("labels")
    val labels: List<CodingReference> = emptyList(),

    @field:JsonProperty("codes")
    val codes: List<CodingReference> = emptyList(),

    /* Extra Uniform Type Identifiers */
    @field:JsonProperty("otherUtis")
    val otherUtis: List<String> = emptyList(),

    /* The revision of the document in the database, used for conflict management / optimistic locking. */
    @field:JsonProperty("rev")
    val rev: String? = null,

    @field:JsonProperty("created")
    val created: Long? = null,

    @field:JsonProperty("modified")
    val modified: Long? = null,

    @field:JsonProperty("author")
    val author: String? = null,

    @field:JsonProperty("responsible")
    val responsible: String? = null,

    @field:JsonProperty("medicalLocationId")
    val medicalLocationId: String? = null,

    @field:JsonProperty("endOfLife")
    val endOfLife: Long? = null,

    @field:JsonProperty("deletionDate")
    val deletionDate: Long? = null,

    /* Reference in object store */
    @field:JsonProperty("objectStoreReference")
    val objectStoreReference: String? = null,

    /* When the document is stored in an external repository, this is the uri of the document in that repository */
    @field:JsonProperty("externalUri")
    val externalUri: String? = null,

    /* The main Uniform Type Identifier of the document (https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE) */
    @field:JsonProperty("mainUti")
    val mainUti: String? = null,

    /* Name of the document */
    @field:JsonProperty("name")
    val name: String? = null,

    /* The document version */
    @field:JsonProperty("version")
    val version: String? = null,

    /* A unique external id (from another external source). */
    @field:JsonProperty("externalUuid")
    val externalUuid: String? = null,

    /* Size of the document file */
    @field:JsonProperty("size")
    val propertySize: Long? = null,

    /* Hashed version of the document */
    @field:JsonProperty("hash")
    val hash: String? = null,

    /* Id of attachment to this document */
    @field:JsonProperty("attachmentId")
    val attachmentId: String? = null

)

