/**
 * ICure Medical Device Micro Service
 *
 * ICure Medical Device Micro Service
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.md.client.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.github.pozo.KotlinBuilder

/**
 * 
 *
 * @param `value` 
 * @param min 
 * @param max 
 * @param ref 
 * @param severity 
 * @param severityCode 
 * @param evolution 
 * @param unit 
 * @param unitCodes 
 * @param comment 
 * @param comparator 
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@KotlinBuilder
data class Measure (

    @field:JsonProperty("value")
    val `value`: Double? = null,

    @field:JsonProperty("min")
    val min: Double? = null,

    @field:JsonProperty("max")
    val max: Double? = null,

    @field:JsonProperty("ref")
    val ref: Double? = null,

    @field:JsonProperty("severity")
    val severity: Int? = null,

    @field:JsonProperty("severityCode")
    val severityCode: String? = null,

    @field:JsonProperty("evolution")
    val evolution: Int? = null,

    @field:JsonProperty("unit")
    val unit: String? = null,

    @field:JsonProperty("unitCodes")
    val unitCodes: Set<CodingReference>? = null,

    @field:JsonProperty("comment")
    val comment: String? = null,

    @field:JsonProperty("comparator")
    val comparator: String? = null

)

