/**
 * ICure Medical Device Micro Service
 *
 * ICure Medical Device Micro Service
 *
 * The version of the OpenAPI document: v2
 *
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.md.client.models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.github.pozo.KotlinBuilder

/**
 *
 *
 * @param telecomType
 * @param telecomNumber
 * @param telecomDescription
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@KotlinBuilder
data class Telecom(

    @field:JsonProperty("telecomType")
    val telecomType: Telecom.TelecomType? = null,

    @field:JsonProperty("telecomNumber")
    val telecomNumber: kotlin.String? = null,

    @field:JsonProperty("telecomDescription")
    val telecomDescription: kotlin.String? = null

) {

    /**
     *
     *
     * Values: mobile,phone,email,fax,skype,im,medibridge,ehealthbox,apicrypt,web,print,disk,other,pager
     */
    enum class TelecomType(val value: kotlin.String) {
        @JsonProperty(value = "mobile")
        mobile("mobile"),
        @JsonProperty(value = "phone")
        phone("phone"),
        @JsonProperty(value = "email")
        email("email"),
        @JsonProperty(value = "fax")
        fax("fax"),
        @JsonProperty(value = "skype")
        skype("skype"),
        @JsonProperty(value = "im")
        im("im"),
        @JsonProperty(value = "medibridge")
        medibridge("medibridge"),
        @JsonProperty(value = "ehealthbox")
        ehealthbox("ehealthbox"),
        @JsonProperty(value = "apicrypt")
        apicrypt("apicrypt"),
        @JsonProperty(value = "web")
        web("web"),
        @JsonProperty(value = "print")
        print("print"),
        @JsonProperty(value = "disk")
        disk("disk"),
        @JsonProperty(value = "other")
        other("other"),
        @JsonProperty(value = "pager")
        pager("pager");
    }
}

