/**
 * ICure Medical Device Micro Service
 *
 * ICure Medical Device Micro Service
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models


import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.github.pozo.KotlinBuilder


/**
 * Encrypted and time-limited Authentication tokens used for inter-applications authentication
 *
 * @param token Encrypted token
 * @param creationTime Validity starting time of the token
 * @param validity Token validity in seconds
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@KotlinBuilder
data class AuthenticationToken (

    /* Encrypted token */
    @field:JsonProperty("token")
    val token: kotlin.String,

    /* Validity starting time of the token */
    @field:JsonProperty("creationTime")
    val creationTime: kotlin.Long,

    /* Token validity in seconds */
    @field:JsonProperty("validity")
    val validity: kotlin.Long

)

