/**
 * ICure Medical Device Micro Service
 *
 * ICure Medical Device Micro Service
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */
package io.icure.kraken.client.models

import io.icure.kraken.client.models.AuthenticationToken
import io.icure.kraken.client.models.Property

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonInclude
import com.github.pozo.KotlinBuilder


/**
 * 
 *
 * @param id the Id of the user. We encourage using either a v4 UUID or a HL7 Id.
 * @param properties Extra properties for the user. Those properties are typed (see class Property)
 * @param roles Roles assigned to this user
 * @param autoDelegations Delegations that are automatically generated client side when a new database object is created by this user
 * @param authenticationTokens Encrypted and time-limited Authentication tokens used for inter-applications authentication
 * @param rev the revision of the user in the database, used for conflict management / optimistic locking.
 * @param deletionDate 
 * @param created 
 * @param name Last name of the user. This is the official last name that should be used for official administrative purposes.
 * @param login Username for this user. We encourage using an email address
 * @param passwordHash Hashed version of the password (BCrypt is used for hashing)
 * @param secret Secret token used to verify 2fa
 * @param use2fa Whether the user has activated two factors authentication
 * @param groupId id of the group (practice/hospital) the user is member of
 * @param healthcarePartyId Id of the healthcare party if the user is a healthcare party.
 * @param patientId Id of the patient if the user is a patient
 * @param deviceId Id of the patient if the user is a patient
 * @param email email address of the user (used for token exchange or password recovery).
 * @param mobilePhone mobile phone of the user (used for token exchange or password recovery).
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@KotlinBuilder
data class User (

    /* the Id of the user. We encourage using either a v4 UUID or a HL7 Id. */
    @field:JsonProperty("id")
    val id: kotlin.String,

    /* Extra properties for the user. Those properties are typed (see class Property) */
    @field:JsonProperty("properties")
    val properties: kotlin.collections.List<Property> = emptyList(),

    /* Roles assigned to this user */
    @field:JsonProperty("roles")
    val roles: kotlin.collections.List<kotlin.String> = emptyList(),

    /* Delegations that are automatically generated client side when a new database object is created by this user */
    @field:JsonProperty("autoDelegations")
    val autoDelegations: kotlin.collections.Map<kotlin.String, kotlin.collections.Set<kotlin.String>> = emptyMap(),

    /* Encrypted and time-limited Authentication tokens used for inter-applications authentication */
    @field:JsonProperty("authenticationTokens")
    val authenticationTokens: kotlin.collections.Map<kotlin.String, AuthenticationToken> = emptyMap(),

    /* the revision of the user in the database, used for conflict management / optimistic locking. */
    @field:JsonProperty("rev")
    val rev: kotlin.String? = null,

    @field:JsonProperty("deletionDate")
    val deletionDate: kotlin.Long? = null,

    @field:JsonProperty("created")
    val created: kotlin.Long? = null,

    /* Last name of the user. This is the official last name that should be used for official administrative purposes. */
    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    /* Username for this user. We encourage using an email address */
    @field:JsonProperty("login")
    val login: kotlin.String? = null,

    /* Hashed version of the password (BCrypt is used for hashing) */
    @field:JsonProperty("passwordHash")
    val passwordHash: kotlin.String? = null,

    /* Secret token used to verify 2fa */
    @field:JsonProperty("secret")
    val secret: kotlin.String? = null,

    /* Whether the user has activated two factors authentication */
    @field:JsonProperty("use2fa")
    val use2fa: kotlin.Boolean? = null,

    /* id of the group (practice/hospital) the user is member of */
    @field:JsonProperty("groupId")
    val groupId: kotlin.String? = null,

    /* Id of the healthcare party if the user is a healthcare party. */
    @field:JsonProperty("healthcarePartyId")
    val healthcarePartyId: kotlin.String? = null,

    /* Id of the patient if the user is a patient */
    @field:JsonProperty("patientId")
    val patientId: kotlin.String? = null,

    /* Id of the patient if the user is a patient */
    @field:JsonProperty("deviceId")
    val deviceId: kotlin.String? = null,

    /* email address of the user (used for token exchange or password recovery). */
    @field:JsonProperty("email")
    val email: kotlin.String? = null,

    /* mobile phone of the user (used for token exchange or password recovery). */
    @field:JsonProperty("mobilePhone")
    val mobilePhone: kotlin.String? = null

)

